### ISSUE TITLE
BM806U拨号咨询

### ISSUE THREAD

**Issue by lppsuixn** [CMCCAdmin/lte-openwrt#1]
你好，请问BM806U TTYUSB 和 AT拨号有相关的教程资料吗？
qmi拨号速度不太理想，想试试其他方案。谢谢

**Comment by CMCCAdmin** [comment]
QMI拨号是最稳定以及快速的，使用ttyUSB也可以不过Openwrt需要装一堆内核驱动，网速不行可以试试锁频段。

**Comment by lppsuixn** [comment]
> QMI拨号是最稳定以及快速的，使用ttyUSB也可以不过Openwrt需要装一堆内核驱动，网速不行可以试试锁频段。

好的，感谢
